refactor and fix bugs and reduce flash write

diff --git a/root/etc/init.d/clash b/root/etc/init.d/clash
--- a/root/etc/init.d/clash
+++ b/root/etc/init.d/clash
@@ -1,8 +1,5 @@
 #!/bin/sh /etc/rc.common
 
-START=99
-STOP=15
-
 # shellcheck source=/dev/null
 . /usr/share/clash/init_env_conf.sh
 
@@ -14,23 +11,28 @@ CUSLIST="/tmp/dnsmasq.d/custom_list.conf"
 CUSLITT="/tmp/dnsmasq.clash"
 CUSLISTV="/var/dnsmasq.d/custom_list.conf"
 CUSLITTV="/var/dnsmasq.clash"
-REAL_LOG="/usr/share/clash/clash_real.txt"
 
-# shellcheck disable=SC2086
+log_msg() {
+	echo "$1" >>"$LOG_FILE"
+}
+log_real_msg() {
+	echo "$1" >>"$REAL_LOG"
+}
+
+
 revert_dns() {
 	#===========================================================================================================================
 	dns_port=$(grep "^ \{0,\}listen:" "$RUNTIME_YAML" | awk -F ':' '{print $3}' 2>/dev/null)
-	uci del_list dhcp.@dnsmasq[0].server=127.0.0.1#$dns_port >/dev/null 2>&1
+	uci del_list dhcp.@dnsmasq[0].server=127.0.0.1#"$dns_port" >/dev/null 2>&1
 	uci set dhcp.@dnsmasq[0].noresolv=0
 	uci delete dhcp.@dnsmasq[0].cachesize
 	rm -rf $CUSLIST $CUSLITT $CUSLISTV $CUSLITTV 2>/dev/null
 	uci commit dhcp
-	echo "Restarting Dnsmasq..." >>$REAL_LOG
+	log_real_msg "Restarting Dnsmasq..."
 	/etc/init.d/dnsmasq restart >/dev/null 2>&1
 	#===========================================================================================================================
 }
 
-# shellcheck disable=SC2086
 add_cron() {
 	# config_type=$(uci get clash.config.config_type 2>/dev/null)
 	#===========================================================================================================================
@@ -38,15 +40,15 @@ add_cron() {
 	grep -qw "/usr/share/clash/kill_watchdog.sh" $CRON_FILE || echo "*/1 * * * * /usr/share/clash/kill_watchdog.sh" >>$CRON_FILE
 	clear=$(uci get clash.config.auto_clear_log 2>/dev/null)
 	if [ "${clear}" -eq 1 ]; then
-		if ! grep -qw "/usr/share/clash/clash.txt" $CRON_FILE; then
-			echo "0 */$(uci get clash.config.clear_time 2>/dev/null) * * * echo '' >/usr/share/clash/clash.txt" >>$CRON_FILE
+		if ! grep -qw "$LOG_FILE" $CRON_FILE; then
+			echo "0 */$(uci get clash.config.clear_time 2>/dev/null) * * * echo '' >$LOG_FILE" >>$CRON_FILE
 		fi
 	fi
 
 	auto=$(uci get clash.config.auto_update 2>/dev/null)
 	if [ "${auto}" -eq 1 ]; then
 		if ! grep -qw "/usr/share/clash/update_all.sh" $CRON_FILE; then
-			echo "0 */$(uci get clash.config.auto_update_time 2>/dev/null) * * * bash /usr/share/clash/update_all.sh >/usr/share/clash/clash.txt 2>&1 &" >>$CRON_FILE
+			echo "0 */$(uci get clash.config.auto_update_time 2>/dev/null) * * * bash /usr/share/clash/update_all.sh >>$LOG_FILE 2>&1 &" >>$CRON_FILE
 		fi
 	fi
 
@@ -54,12 +56,12 @@ add_cron() {
 	if [ "${auto_geoip}" -eq 1 ]; then
 		day=$(uci get clash.config.geoip_update_day 2>/dev/null)
 		week=$(uci get clash.config.geo_update_week 2>/dev/null)
-		if [ -z $week ]; then
+		if [ -z "$week" ]; then
 			update_week="*"
 		else
 			update_week=$week
 		fi
-		if [ -z $day ]; then
+		if [ -z "$day" ]; then
 			update_day="*"
 		else
 			update_day=$day
@@ -76,24 +78,27 @@ add_cron() {
 del_cron() {
 	#===========================================================================================================================
 	sed -i '/clash-watchdog.sh/d' $CRON_FILE
-	sed -i '/update_all.sh/d' $CRON_FILE
-	sed -i '/clash.txt/d' $CRON_FILE
+	name="/usr/share/clash/update_all.sh"
+	escaped_fn=$(echo "$name"|sed 's/\//\\\//g')
+	sed -i "/$escaped_fn/d" $CRON_FILE
+	escaped_fn=$(echo "$LOG_FILE"|sed 's/\//\\\//g')
+	sed -i "/$escaped_fn/d" $CRON_FILE
 	/etc/init.d/cron restart
 	#===========================================================================================================================
 }
 
 select_config() {
 	#===========================================================================================================================
+	log_real_msg "Checking config file..."
 	# config_type=$(uci get clash.config.config_type 2>/dev/null)
-	echo "Checking config file..." >>$REAL_LOG
 
 	if [ -s "$CONFIG_YAML_PATH" ]; then
 		cp "$CONFIG_YAML_PATH" "$RUNTIME_YAML" 2>/dev/null
 	else
 		if [ -s "$RUNTIME_YAML" ]; then
-			echo "CAUTION: Customized config file not found! Use old config file now!" >>$REAL_LOG
+			log_real_msg "CAUTION: Customized config file not found! Use old config file now!"
 		else
-			echo "ERROR: Config files not exist or empty!" >>$REAL_LOG
+			log_real_msg "ERROR: Config files not exist or empty!"
 			exit 21
 		fi
 	fi
@@ -118,7 +123,6 @@ ip_rules() {
 	#===========================================================================================================================
 }
 
-# shellcheck disable=SC2086
 yml_dns_change() {
 	#===========================================================================================================================
 	dns_port=$(grep "^ \{0,\}listen:" "$RUNTIME_YAML" | awk -F ':' '{print $3}' 2>/dev/null)
@@ -129,26 +133,26 @@ yml_dns_change() {
 	fi
 
 	if [ "$dnsforwader" -ne 0 ]; then
-		echo "Setting dns forwarder..." >>$REAL_LOG
+		log_real_msg "Setting up DNS forwarder..."
 		if [ "${dns_port}" -eq 53 ]; then
-			uci del_list dhcp.@dnsmasq[0].server=127.0.0.1#$dns_port >/dev/null 2>&1
+			uci del_list dhcp.@dnsmasq[0].server=127.0.0.1#"$dns_port" >/dev/null 2>&1
 			uci add_list dhcp.@dnsmasq[0].server=127.0.0.1#5300 >/dev/null 2>&1
 		else
-			uci del_list dhcp.@dnsmasq[0].server=127.0.0.1#$dns_port >/dev/null 2>&1
-			uci add_list dhcp.@dnsmasq[0].server=127.0.0.1#$dns_port >/dev/null 2>&1
+			uci del_list dhcp.@dnsmasq[0].server=127.0.0.1#"$dns_port" >/dev/null 2>&1
+			uci add_list dhcp.@dnsmasq[0].server=127.0.0.1#"$dns_port" >/dev/null 2>&1
 		fi
 		uci delete dhcp.@dnsmasq[0].resolvfile
 		uci set dhcp.@dnsmasq[0].noresolv=1
 		uci commit dhcp
 
 		if [ "$dnscache" -eq 0 ]; then
-			echo "Disabling dns cache..." >>$REAL_LOG
+			log_real_msg "Disabling DNS cache..."
 			uci set dhcp.@dnsmasq[0].cachesize=0
 			uci commit dhcp
 		fi
 	elif [ "$dnsforwader" -ne 1 ]; then
 		if [ "$dnscache" -eq 0 ]; then
-			echo "Disabling dns cache..." >>$REAL_LOG
+			log_real_msg "Disabling DNS cache..."
 			uci set dhcp.@dnsmasq[0].cachesize=0
 			uci commit dhcp
 		fi
@@ -362,10 +366,8 @@ restore() {
 	sh /usr/share/clash/restore.sh >/dev/null 2>&1
 }
 
-# shellcheck disable=SC2086
 start() {
 	#===========================================================================================================================
-	lang=$(uci get luci.main.lang 2>/dev/null)
 	enable=$(uci get clash.config.enable 2>/dev/null)
 	core=$(uci get clash.config.core 2>/dev/null)
 	mode=$(uci get clash.config.mode 2>/dev/null)
@@ -376,32 +378,32 @@ start() {
 	fi
 
 	if [ "${enable}" -ne 1 ]; then
-		echo "  $(date "+%Y-%m-%d %H:%M:%S") - client is NOT enabled, will not start." >>/usr/share/clash/clash.txt
-		echo "ERROR: Client is NOT enabled, will not start." >>$REAL_LOG
+		echo "  $(date "+%Y-%m-%d %H:%M:%S") - client is NOT enabled, will not start." >>"$LOG_FILE"
+		log_real_msg "ERROR: Client is NOT enabled, will not start."
 		exit 100
 	fi
 
-	echo "Starting client..." >>$REAL_LOG
+	printf "\nStarting client...\n" >>"$REAL_LOG"
 	select_config >/dev/null 2>&1
 	sleep 1
 
-	if [ "${core}" -eq 1 ] && [ ! -f $CORE_CLASH ]; then
-		echo "  $(date "+%Y-%m-%d %H:%M:%S") - Can NOT find clash core ($CORE_CLASH), plz install it from update page" >>/usr/share/clash/clash.txt
-		echo "Can NOT find clash core ($CORE_CLASH), plz install it from update page" >>$REAL_LOG
+	if [ "${core}" -eq 1 ] && [ ! -f "$CORE_CLASH" ]; then
+		echo "  $(date "+%Y-%m-%d %H:%M:%S") - Can NOT find clash core ($CORE_CLASH), plz install it from update page" >>"$LOG_FILE"
+		log_real_msg "Can NOT find clash core ($CORE_CLASH), plz install it from update page"
 		exit 11
-	elif [ "${core}" -eq 3 ] && [ ! -f $CORE_CLASH_TUN ]; then
-		echo "  $(date "+%Y-%m-%d %H:%M:%S") - Can NOT find Tun core ($CORE_CLASH_TUN)" >>/usr/share/clash/clash.txt
-		echo "Can NOT find Tun core ($CORE_CLASH_TUN)" >>$REAL_LOG
+	elif [ "${core}" -eq 3 ] && [ ! -f "$CORE_CLASH_TUN" ]; then
+		echo "  $(date "+%Y-%m-%d %H:%M:%S") - Can NOT find Tun core ($CORE_CLASH_TUN)" >>"$LOG_FILE"
+		log_real_msg "Can NOT find Tun core ($CORE_CLASH_TUN)"
 		exit 13
-	elif [ "${core}" -eq 4 ] && [ ! -f $CORE_CLASH_DTUN ]; then
-		echo "  $(date "+%Y-%m-%d %H:%M:%S") - Can NOT find Tun core ($CORE_CLASH_DTUN)" >>/usr/share/clash/clash.txt
-		echo "Can NOT find Tun core ($CORE_CLASH_DTUN)" >>$REAL_LOG
+	elif [ "${core}" -eq 4 ] && [ ! -f "$CORE_CLASH_DTUN" ]; then
+		echo "  $(date "+%Y-%m-%d %H:%M:%S") - Can NOT find Tun core ($CORE_CLASH_DTUN)" >>"$LOG_FILE"
+		log_real_msg "Can NOT find Tun core ($CORE_CLASH_DTUN)"
 		exit 14
 	fi
 
 	if [ ! -s "$RUNTIME_YAML" ]; then
-		echo "  $(date "+%Y-%m-%d %H:%M:%S") - Invalid config.yaml, empty or not found" >>/usr/share/clash/clash.txt
-		echo "  ERROR: invalid config.yaml, empty or not found" >>$REAL_LOG
+		echo "  $(date "+%Y-%m-%d %H:%M:%S") - Invalid config.yaml, empty or not found" >>"$LOG_FILE"
+		log_real_msg "  ERROR: invalid config.yaml, empty or not found"
 		exit 21
 	fi
 
@@ -409,8 +411,8 @@ start() {
 	check >/dev/null 2>&1
 	custom_list >/dev/null 2>&1
 	if [ "$core" -eq 4 ] || [ "$core" -eq 3 ]; then
-		if [ $tun_mode -eq 0 ]; then
-			echo "Enabling TUN..." >>$REAL_LOG
+		if [ "$tun_mode" -eq 0 ]; then
+			log_real_msg "Enabling TUN..."
 			uci set clash.config.tun_mode="1" && uci set clash.config.stack="system" && uci commit clash
 		fi
 	fi
@@ -418,18 +420,18 @@ start() {
 	enable_dns=$(uci get clash.config.enable_dns 2>/dev/null)
 
 	if ! grep -q "^ {0,}listen:" "$RUNTIME_YAML" || ! grep -q "^ {0,}enhanced-mode:" "$RUNTIME_YAML" || ! grep "^ {0,}dns:" "$RUNTIME_YAML"; then
-		if [ $enable_dns -eq 0 ]; then
+		if [ "$enable_dns" -eq 0 ]; then
 			uci set clash.config.enable_dns="1" && uci commit clash
-			echo "Enabling custom DNS..." >>$REAL_LOG
+			log_real_msg "Enabling custom DNS..."
 		fi
 	fi
 
 	if grep -qE '^ {0,}rule-providers:' "$RUNTIME_YAML" && [ "$(uci get clash.config.core)" -ne 4 ]; then
-		if [ -f $CORE_CLASH_DTUN ]; then
+		if [ -f "$CORE_CLASH_DTUN" ]; then
 			uci set clash.config.core="4" && uci commit clash
 			sleep 1
 		else
-			echo "ERROR: Your current config only support DTUN core" >>$REAL_LOG
+			log_real_msg "ERROR: Your current config only support DTUN core"
 			remove_mark >/dev/null 2>&1
 			sleep 1
 			exit 24
@@ -438,11 +440,11 @@ start() {
 
 	tmp_rule=$(grep -E '^ {0,}script:' "$RUNTIME_YAML")
 	if [ -n "$tmp_rule" ] && [ "$(uci get clash.config.core)" -ne 4 ]; then
-		if [ -f $CORE_CLASH_DTUN ]; then
+		if [ -f "$CORE_CLASH_DTUN" ]; then
 			uci set clash.config.core="4" && uci commit clash
 			sleep 1
 		else
-			echo "ERROR: Your current config only support DTUN core" >>$REAL_LOG
+			log_real_msg "ERROR: Your current config only support DTUN core"
 			remove_mark >/dev/null 2>&1
 			exit 24
 		fi
@@ -456,13 +458,13 @@ start() {
 
 	yml_change >/dev/null 2>&1
 
-	if [ ! -f $GEOIP_FILE ]; then
-		echo "ERROR: Can NOT find Country.mmdb" >>$REAL_LOG
+	if [ ! -f "$GEOIP_FILE" ]; then
+		log_real_msg "ERROR: Can NOT find Country.mmdb"
 		exit 31
 	fi
 
 	if [ ! -f "$RUNTIME_YAML" ]; then
-		echo "ERROR: Can NOT find config.yaml" >>$REAL_LOG
+		log_real_msg "ERROR: Can NOT find config.yaml"
 		remove_mark >/dev/null 2>&1
 		exit 21
 	fi
@@ -475,40 +477,42 @@ start() {
 
 	core_type=$(uci get clash.config.core)
 	if [ "$core_type" -eq 1 ]; then
-		nohup $CORE_CLASH -d "$CLASH_CONF_DIR" >/usr/share/clash/clash.txt 2>&1 &
-		echo "Clash core started" >>$REAL_LOG
+		nohup "$CORE_CLASH" -d "$CLASH_CONF_DIR" >>"$CORE_LOG_FILE" 2>&1 &
+		log_real_msg "Clash core started."
 	elif [ "$core_type" -eq 3 ]; then
-		nohup $CORE_CLASH_TUN -d "$CLASH_CONF_DIR" >/usr/share/clash/clash.txt 2>&1 &
-		echo "Clash core started" >>$REAL_LOG
+		nohup "$CORE_CLASH_TUN" -d "$CLASH_CONF_DIR" >>"$CORE_LOG_FILE" 2>&1 &
+		log_real_msg "Clash core started."
 	elif [ "$core_type" -eq 4 ]; then
-		nohup $CORE_CLASH_DTUN -d "$CLASH_CONF_DIR" >/usr/share/clash/clash.txt 2>&1 &
-		echo "Clash core started" >>$REAL_LOG
+		nohup "$CORE_CLASH_DTUN" -d "$CLASH_CONF_DIR" >>"$CORE_LOG_FILE" 2>&1 &
+		log_real_msg "Clash core started."
 	fi
 
 	ln -s /usr/share/clash/yacd /www/luci-static/yacd 2>/dev/null
 
-	echo "Setting up clash iptables..." >>$REAL_LOG
+	log_real_msg "Setting up clash iptables..."
 	rules >/dev/null 2>&1
 
-	echo "Restarting dnsmasq..." >>$REAL_LOG
+	log_real_msg "Restarting dnsmasq..."
 	/etc/init.d/dnsmasq restart >/dev/null 2>&1
 
 	restore >/dev/null 2>&1
 
-	echo "Setting up cron jobs..." >>$REAL_LOG
+	log_real_msg "Setting up cron jobs..."
 	add_cron
 
 	sleep 1
-	echo "Check if clash is running..." >>$REAL_LOG
+	printf "Check if clash is running..." >>"$REAL_LOG"
 	if ! pidof clash_core >/dev/null; then
+		printf "%8s\n" "no" >>"$REAL_LOG"
 		remove_mark 2>/dev/null
 		for p in $(pgrep clash_core); do
 			kill -9 $p 2>/dev/null
 		done
-		echo "Failed to start clash, please check the log" >>$REAL_LOG
+		printf "Failed to start clash, please check the log.\n" >>"$REAL_LOG"
 		exit 101
 	fi
-	echo "Clash Started Successfuly" >>$REAL_LOG
+	printf "%8s\n" "yes" >>"$REAL_LOG"
+	printf "Clash Started Successfuly.\n" >>"$REAL_LOG"
 	#===========================================================================================================================
 }
 
@@ -683,29 +687,30 @@ stop() {
 
 	sed -i '/#START/,/#END/d' "$LIST" 2>/dev/null
 
-	echo "Stopping client..." >>$REAL_LOG
+	log_real_msg "Stopping client..."
 	sleep 1
 	remove_mark >/dev/null 2>&1
 
-	echo "Removing clash iptables rules..." >>$REAL_LOG
+	log_real_msg "Removing clash iptables rules..."
 
 	bash /usr/share/clash/backup.sh >/dev/null 2>&1
 
 	kill -9 "$(pidof clash_core | sed "s/$//g")" 2>/dev/null
-	echo "Clash core stoped successfully" >>$REAL_LOG
+	log_real_msg "Clash core stoped."
 
 	rm -rf /www/luci-static/yacd 2>/dev/null
 
-	echo "Deleting cron job..." >>$REAL_LOG
+	log_real_msg "Deleting cron job..."
 	del_cron >/dev/null 2>&1
 	sleep 1
 
-	echo "" >/usr/share/clash/clash.txt >/dev/null 2>&1
+	# clear log
+	echo "" >"$LOG_FILE" >/dev/null 2>&1
 
 	echo "0" >/usr/share/clash/logstatus_check >/dev/null 2>&1
 
-	echo "  $(date "+%Y-%m-%d %H:%M:%S") - CLIENT IS DISABLED " >>/usr/share/clash/clash.txt
-	echo "Client is Disabled " >>$REAL_LOG
+	log_real_msg "  $(date "+%Y-%m-%d %H:%M:%S") - CLIENT IS DISABLED "
+	log_real_msg "Client is Disabled."
 
 	if pidof clash_core >/dev/null; then
 		kill "$(pidof clash_core)" >/dev/null 2>&1 || kill -9 "$(pgrep clash_core)" >/dev/null 2>&1
